version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    image: animedia-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rails_ani_production
      MYSQL_USER: rails_ani
      MYSQL_PASSWORD: sV6Wkq2N
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
  app:
    build:
      context: ./backend
      dockerfile: ./../infra/rails/Dockerfile
    image: rails-ani
    volumes:
      - ./backend/:/backend
    ports:
      - "80:80"
    depends_on:
      - db
    stdin_open: true
    tty: true
  web:
    build:
      context: ./frontend
      dockerfile: ./../infra/nuxt/Dockerfile
    image: nuxt-ani
    ports:
      - "3000:3000"
    tty: true
    environment:
    - HOST=0.0.0.0
    - CHOKIDAR_USEPOLLING=true
volumes:
  db-data: